# Ryan Kim Flag Project
import turtle
place = input("Which flag would you lie? (Japan, Italy, Netherlands)") #ask for which flag I should draw
t = turtle.Turtle() #set up turtle
t.speed(100)#make turtle fast
if place.lower() == 'japan': #flag of Japan
      t.pencolor('red')
      t.fillcolor('red')
      t.begin_fill()
      t.circle(60)
      t.end_fill()
  
elif place.lower() == 'netherlands': #flag of netherlands
      t.penup()
      t.pencolor('red')
      t.fillcolor('red')
      t.begin_fill()
      t.goto(-100,20)
      t.pendown()
      t.fd(200)
      t.rt(90)
      t.fd(20)
      t.rt(90)
      t.fd(200)
      t.rt(90)
      t.fd(20)
      t.end_fill()
      t.penup()
      t.fillcolor('blue')
      t.begin_fill()
      t.goto(-100,-40)
      t.pendown()
      t.pencolor('blue')
      t.fd(20)
      t.rt(90)
      t.fd(200)
      t.rt(90)
      t.fd(20)
      t.rt(90)
      t.fd(200)
      t.end_fill()
      

elif place.lower() == 'italy': #flag of Italy
      t.penup()
      t.fillcolor('green')
      t.pencolor('green')
      t.begin_fill()
      t.goto(-50,50)
      t.pendown()
      t.rt(90)
      t.fd(100)
      t.lt(90)
      t.fd(50)
      t.lt(90)
      t.fd(100)
      t.lt(90)
      t.fd(50)
      t.end_fill()
      t.penup()
      t.fillcolor('red')
      t.begin_fill()
      t.goto(50,50)
      t.pendown()
      t.pencolor('red')
      t.lt(90)
      t.fd(100)
      t.lt(90)
      t.fd(50)
      t.lt(90)
      t.fd(100)
      t.lt(90)
      t.fd(50)
      t.end_fill()

else:#if specified flag is not found
      print('We can\' print this code, sorry!')
      turtle.bye()
     
input()